services:
  parser:
    build: .
    ports:
      - "8000:8000"

    develop:
      # Create a `watch` configuration to update the application in the container
      # https://docs.docker.com/compose/file-watch/#compose-watch-versus-bind-mounts
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: ../src
          target: /app
          ignore:
            - .venv/
            - .idea/
            - .git/

        # Rebuild the image if dependencies change by checking uv.lock
        - action: rebuild
          path: ../uv.lock

  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
